language: node_js
node_js: 6

env:
  global:
  - secure: "kPqKtmBHdnwttnjoimMH/U4009cLzeYi6XaxIaNCuka6dnRHUcaID8Yo3GBCZUXmZfSGzJH2SLb3Ylyn3kH46LQPH5lfExRTDMIKVCrSmmp9NgunpUuC0in8NlvZroONX7RP84zCqwhBpf//eoXhog1ZZjjcEhSIpX6PSM6kXBJUATgcSR3/8KxJwoya46px7ZcKZxAEYdwppttzFMjG1hECRrHqRS7RPVbJCVGzUxaSX8ungV6Yz7oeu44OTqrcvFMleqGsu1aLEWuzc1ILWDdh6eLpFse3pULCVk1GDI18fuDh5B5oVJhPdKx1aQO1XtyRcIgW5Bwwhb4bTOGJD8fHklxInreuTxHGTVlXJD0JwaUxarQlKOYn8FLVo31xMf7BymAJFeABuY5PIz8iuwJ7T/+WM0WOoVmAkDj/eltXzYAFthrO5UrUGTpRnN8n6+OxbM8c25Bu95MHKn1RXQMvQl8952bruutQqZkgGIFoikopcYJwaxEpXlX6CbjMwv4sj1gZ+tOPNu6a8jbXBLdKxBrvZcdmyRyR2laHnPM8i47qLr/sHZSUu/AZ42dr8VT2T15GeThWBUt6mBzmTcVqVPJKbFnjTon2iZ7DK+tdXzS4ua4+25iVL84qSdNQSlMO5lTLUZagFFEalmjhXmRd2ZzVHqAYGiFJYx0UbEs="

deploy:
  skip_cleanup: true
  provider: script
  script: ./resources/publish.sh
  on:
    branch: source
